(env) C:\Users\alexander.trukhachev\PycharmProjects\pytraining_v001\test>py.test --alluredir allure-results test_groups.py
Traceback (most recent call last):
  File "c:\users\alexander.trukhachev\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\alexander.trukhachev\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexander.trukhachev\PycharmProjects\pytraining_v001\env\Scripts\py.test.exe\__main__.py", line 7, in <module>
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\manager.py", line 300, in load_setuptools_entrypoints
    self.register(plugin, name=ep.name)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\_pytest\config\__init__.py", line 436, in register
    ret: Optional[str] = super().register(plugin, name)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\manager.py", line 127, in register
    hook._maybe_apply_history(hookimpl)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\hooks.py", line 333, in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\alexander.trukhachev\pycharmprojects\pytraining_v001\env\lib\site-packages\allure_pytest\plugin.py", line 48, in pytest_addoption
    severities = [x.value for x in list(allure.severity_level)]
AttributeError: module 'allure' has no attribute 'severity_level'
